stages:
  - build-develop
  - deploy-develop

build-develop:
  stage: build-develop
  image: node:latest
  script:
    - npm install --legacy-peer-deps
    - npm run build
  only:
    - develop
    - merge_requests
  tags: [develop]

deploy-develop:
  stage: deploy-develop
  image: ubuntu
  needs: ['build-develop']
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
    - apt-get install rsync -y -qq
    - apt-get install curl -y -qq
  script:
    - echo "Deploying to server"
    - ssh -i ~/.ssh/gitlab -o StrictHostKeyChecking=no $SSH_USER@$VM_IPADDRESS "git pull && npm && npm run build"
    - echo "Deployed"
  only:
    - develop
  tags: [develop]
