variables:
  IMAGE_NAME: khoavio/reading-time
  IMAGE_TAG: img2
stages:
  - build-develop
  - build-image
  - deploy-develop

build-develop:
  stage: build-develop
  image: node:latest
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - /home/gitlab-runner/
  only:
    - develop
    - merge_requests
  tags: [develop]

build-image:
  # needs: ['build-develop']
  stage: build-image
  image: docker
  services:
    - docker:dind
  before_script:
    - docker login -u khoavio -p qvak472000
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
  only:
    - develop
  tags: [develop]

deploy-develop:
  stage: deploy-develop
  image: ubuntu
  # needs: ['build-image']
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - bash -c 'ssh-add <(echo "$SSH_PRIVATE_KEY")'
    - mkdir -p ~/.ssh
    - ssh-keyscan -H 139.59.102.34 >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh root@139.59.102.34 "docker login -u khoavio -p $REGISTRY_PASS && docker run -p 8080:8080 -d my-node-app"
  only:
    - develop
  tags: [develop]
