stages:
  - build-develop
  - deploy-develop

build-develop:
  stage: build-develop
  image: node:latest
  script:
    - npm install --legacy-peer-deps
    - npm run build
  only:
    - develop
    - merge_requests
  tags: [develop]

deploy-develop:
  stage: deploy-develop
  image: ubuntu
  needs: ['build-develop']
  script:
    - echo "Deploying to server"
    - npm run build
    - echo "Deployed"
  only:
    - develop
  tags: [develop]
