stages:
  - build-develop
  - deploy-develop

build-develop:
  stage: build-develop
  image: node:latest
  script:
    - npm install --legacy-peer-deps
    - npm run build
  only:
    - develop
    - merge_requests
  tags: [develop]

deploy-develop:
  stage: deploy-develop
  image: ubuntu
  needs: ['build-develop']
  script:
    - echo "Deploying to server"
    - "cd readingtime-web-be && git pull develop && npm install && npm run build"
    - echo "Deployed"
  environment:
    name: production
    url: http://164.92.107.189

  only:
    - develop
  tags: [develop]
